server:
  port: 8085
spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      routes:
        - id: DEMO-SERVICE
          uri: http://localhost:9090
          predicates:
            - Path=/demo/**
